version: '3'

services:
  cnn_mnist:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8889:8888"
    volumes:
      - .:/app
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''
